#!/usr/bi/env bash
# Displays the content of the file `/etc/passwd`.
#  only displays username, user id, home directry path for the user

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
