#!/usr/bin/env bash
# Loops from 1 to 10 and:
#  displays "bad luck" for the 4th loop iteration
#  dislays "good luck" for the 8th loop iteration
#  dislays "Best School" for the other iteration


count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
